### ISSUE TITLE
Typo in command name

### ISSUE THREAD

**Issue by srepn** [astorm/magento2-tutorial-plugin#2]
There is no "bin/magento ps:tutorial-plugin-installed" ( from http://alanstorm.com/magento_2_object_manager_plugin_system/ ) command, maybe  should be "bin/magento ps:tutorial-installed" or vice versa.

**Comment by astorm** [comment]
If I ever become more than moderately successful, I'm going to pay someone to follow a feed of my activity on the internet and fix any typos that come my way. 

@serhiirepin Fixing in the repo makes the most sense.  I'll try to get to it in the next few days, and am open to pull request.  Hope we didn't cause too much confusion.

**Comment by astorm** [comment]
Thanks again for the heads up @serhiirepin.  I changed the code here to match the tutorial text.  Closing out, but if there are still problems please don't hesitate to reopen

**Comment by srepn** [comment]
:+1: , @astorm . 
Next time I would like to create PR. ;)
